module.exports = [
    {
        Name: "Daily Box",
        ShowName: "🎁 Daily Box",
        InfoImage: `https://i.imgur.com/m9aDic8.png`,
        Description: "You Get This Box Whenever You Use The Daily Command, Gives You **500 to 1500 <:Dogecoin_Logo:860033532327231488>** Once You Use It.",
        IDs: ['daily', 'dailybox'],
        InShop: false,
        Buyable: false,
        BuyPrice: false,
        Sellable: true,
        SellPrice: 2500,
        Usable: true,
    },
    {
        Name: "Mystery Gift",
        ShowName: "📦 Mystery Gift",
        InfoImage: `https://i.imgur.com/m9aDic8.png`,
        Description: "A Gift From The Doge God Whenever You Hit Level 3.",
        IDs: ['mysterygift'],
        InShop: false,
        Buyable: false,
        BuyPrice: false,
        Sellable: false,
        SellPrice: false,
        Usable: true,
    },
]